name: CRT Onboarding
description: Submit an onboarding request
body:
  - type: input
    id: "repository_name"
    attributes:
      label: Repository Name
      description: What is the name of the repository that you would like to onboard?
    validations:
      required: true
  - type: input
    id: "repository_link"
    attributes:
      label: Link to Repository
      description: Link/URL to Repository
    validations:
      required: true

  - type: dropdown
    id: "repo_type"
    attributes:
      label: What type of repository is this? (Community Edition, Internal, or Enterprise?)
      multiple: false
      default: 0
      options:
        - "CE"
        - "INT"
        - "ENT"
    validations:
      required: true
  - type: textarea
    id: "release_approvers"
    attributes:
     label: Description
     description: Please include the github usernames that you would like to have added as release approvers
    validations:
      required: true
  - type: markdown
    attributes:
      value: |
        ---
  - type: checkboxes
    id: link
    attributes:
     label: What do you plan to release? Go Binaries, Docker Images, Redhat? 
     description: Please tick all the types of artifacts
     options:
      - label: Go Binaries
      - label: Docker Images
      - label: RedHat Images
      - label: Linux Packages

