name: Add Team to Repo on Issue Opened

on:
  issues:
    types:
      - opened
      - reopened

jobs:
  add_team_to_repo:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Extract team_name from issue body
        id: extract_team_name
        run: |
          # Extract the issue body
          ISSUE_BODY=$(jq -r .issue.body $GITHUB_EVENT_PATH)
          
          # Print the raw issue body for debugging
          echo "Raw Issue Body: $ISSUE_BODY"
          
          # Use sed to extract the team name after "### Team Name"
          TEAM_NAME=$(echo "$ISSUE_BODY" | sed -n '/### Team Name/,/^$/p' | sed '1d' | sed 's/^[[:space:]]*//')

          # Debug output for the extracted team_name
          echo "Extracted team name: $TEAM_NAME"

          # Set the extracted team_name as an environment variable
          echo "team_name=${TEAM_NAME}" >> $GITHUB_ENV

      - name: Debug team name
        run: |
            echo "Team name extracted: ${{ env.team_name }}"

      - name: Add team with write access to the repo
        if: ${{ env.team_name != '' }}
        run: |
          curl -X PUT -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
          -H "Accept: application/vnd.github.v3+json" \
          -d '{"permission": "push"}' \
          "https://api.github.com/orgs/${{ github.repository_owner }}/teams/$TEAM_NAME/repos/${{ github.repository_owner }}/${{ github.repository }}"
        env:
          TEAM_NAME: ${{ env.team_name }}

