name: Backport Assistant Runner

on:
  pull_request:
    types:
      - closed
      - labeled

jobs:
  backport:
    runs-on: ubuntu-latest
    container: hashicorpdev/backport-assistant:0.3.5
    if: github.event.pull_request.merged
    steps:
      - name: print event
        env:
          EVENT: ${{ toJson(github.event) }}
        run: |
          echo "$EVENT"
