name: Workflow Run

on:
  workflow_run:
    workflows:
      - "Workflow Dispatch"
      - "Reusable workflow"
    types: [completed]

jobs:
  example_job:
    name: Shows if emit events
    runs-on: ubuntu-latest
    # Map the job outputs to step outputs
    steps:
      - id: step1
        run: echo "${{toJSON(github.event)}}"
